### ISSUE TITLE
ST3: Function arguments are highlighted for '->', but not '!->'

### ISSUE THREAD

**Issue by kriomant** [paulmillr/LiveScript.tmbundle#27]
Parens and argument names are highlighted in the following code

    f = (a) -> a

but not in

    f = (a) !-> a

**Comment by farzher** [comment]
This isn't an issue anymore

![image](https://cloud.githubusercontent.com/assets/1005136/9239096/77b48672-4126-11e5-832b-0af6bf8c1d40.png)
