### ISSUE TITLE
Methods with no parameters are highlighted as properties

### ISSUE THREAD

**Issue by hyphz** [paulmillr/LiveScript.tmbundle#36]
A method written as:

method: ((m) -> m)

Has the name "method" shown in green. But a method with no parameters, as:

method: ( -> (@x++))

Has the name shown in white, as if it were a property.

**Comment by farzher** [comment]
Yeah it works without parens. But not with

![image](https://cloud.githubusercontent.com/assets/1005136/9239138/ee4bf66c-4126-11e5-9a81-0e060ba370d9.png)

**Comment by vendethiel** [comment]
Is it worth making this work? (Without the obvious but unreliable `\(?`)
