### ISSUE TITLE
Keywords such as "class" and "public" are over-highlighted

### ISSUE THREAD

**Issue by chrisvfritz** [paulmillr/LiveScript.tmbundle#41]
For example, `create-class` highlights `class` and `public-path` highlights `public`, even though these aren't being used as keywords in their current context. To fix this, we should probably enforce word boundaries on either side, excluding the `-` character.

As a reference, [this older project](https://github.com/joneshf/sublime-livescript) does seem to handle this case correctly.

**Comment by farzher** [comment]
This should be fixed since 3 weeks ago from my massive pull request (:

https://github.com/paulmillr/LiveScript.tmbundle/pull/39
