### ISSUE TITLE
build error: "command not found: livescript"

### ISSUE THREAD

**Issue by bestian** [paulmillr/LiveScript.tmbundle#44]
hi, i'm using sublime text & livescript on both Windows and OS X
in both case, livescript compiler are names "lsc", not "livescript"
perhaps it's why the build system in sublime text package doesn't work.

**Comment by vendethiel** [comment]
(Sorry, I'm not sure anyone (plans to) maintains this package)

**Comment by bestian** [comment]
if i fork and fix and send pull-reuqust to you, will you double-check it, and update the published version if the code is right?

**Comment by vendethiel** [comment]
No
